# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('rank', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_btc', models.DecimalField(decimal_places=16, max_digits=24)),
                ('day_volume_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('market_cap_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_supply', models.DecimalField(decimal_places=8, max_digits=24)),
                ('total_supply', models.DecimalField(decimal_places=8, max_digits=24)),
                ('percent_change_1h', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent_change_7d', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
