"""
Django settings for episectrad project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from celery.beat import crontab

import environ


env = environ.Env()
root = environ.Path(__file__) - 2  # type: Callable[[*str], str]
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3&ivww#qg4pvp7ia369yntst=xcw2z^*$o3fc!cqb@*j05n5is'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'dashboard',
    'core',
    'hijack_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_otp.middleware.OTPMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'episectrad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [root("templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'episectrad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'episectrad',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # ('node_modules', os.path.join(BASE_DIR, 'node_modules')),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = "/dashboard/login"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

AUTH_USER_MODEL = "dashboard.User"

# emails validation
VALIDATE_EMAILS = env.bool("VALIDATE_EMAILS", default=not DEBUG)
VALIDATE_EMAILS_MAILBOXES = env.bool("VALIDATE_EMAILS_MAILBOXES", default=False)
MAILGUN_PUBLIC_API_KEY = env.str("MAILGUN_PUBLIC_API_KEY", default="pubkey-796866a6835d81be6a6e128121b93df5")
BLOCKED_EMAIL_DOMAINS = env.tuple("BLOCKED_EMAIL_DOMAINS", default=(
    "qq.com",
    "163.com"
))

# Hijack
HIJACK_LOGIN_REDIRECT_URL = "/dashboard/"
HIJACK_LOGOUT_REDIRECT_URL = "/voynich-manuscript/dashboard/user/"
HIJACK_REGISTER_ADMIN = False
HIJACK_AUTHORIZE_STAFF = True
HIJACK_ALLOW_GET_REQUESTS = True

# Celery configuration
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 6 * 3600}
CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND", default="django-cache")
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_SEND_TASK_EVENTS = True
# CELERY_BEAT_SCHEDULE = {
#     "update_metrics": {
#         "task": "core.tasks.update_token_metrics",
#         "schedule": crontab(minute="*/5")
#     },
#     "sync_with_payments_service": {
#         "task": "dashboard.tasks.sync_with_payments_service",
#         "schedule": crontab(minute="*/5")
#     },
# }


# email config
DEFAULT_FROM_EMAIL = "EpisecTrading <kss_alexander2@outlook.com>"
CONTACT_EMAIL = DEFAULT_FROM_EMAIL
